
name: 🐞 CLI Issue
description: Report an Issue with the CLI
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this CLI bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Add descriptions
      value: 'Briefly Describe the bug you found'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the problems
      placeholder: Add screenshots
      value: 'Add screenshots'
  - type: dropdown
    id: browsers
    attributes:
      label: What terminal are you seeing the problem on?
      multiple: true
      options:
        - Git Bash
        - Powershell
        - Command Prompt
        - Windows Terminal
        - WSL
        - Other
  - type: checkboxes
    id: self-grab
    attributes:
      label: Self - Grab
      description: By checking this box, you can fix this bug
      options:
        - label: I would like to work on this issue
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
